-- 코드를 입력하세요
SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, FLOOR(((DAILY_FEE * (100 - DISCOUNT_RATE)) / 100) * 30) FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC 
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCC.CAR_TYPE IN ("SUV", "세단") AND (CRCC.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                                         WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'))
                                          AND DURATION_TYPE = "30일 이상" 
GROUP BY CRCC.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CRCC.CAR_TYPE, CRCC.CAR_ID DESC