# -- 코드를 입력하세요
SELECT FP.PRODUCT_ID, PRODUCT_NAME, PRICE * SUM(AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP JOIN FOOD_ORDER FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID