-- 코드를 작성해주세요
SELECT SUM(SCORE) SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES E JOIN HR_DEPARTMENT D JOIN HR_GRADE G
ON E.DEPT_ID = D.DEPT_ID AND E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
HAVING SUM(SCORE) >= ALL(SELECT SUM(SCORE) FROM HR_GRADE GROUP BY EMP_NO)